#!/usr/bin/env sh
#MISE description="Format rust files"
#MISE tools.rust="nightly"

set -e

cargo sort --config .config/tomlfmt.toml
cargo +nightly fmt --all -- --config-path .config/rustfmt.toml
cargo clippy --fix --all-targets --all-features --allow-dirty --allow-staged --allow-no-vcs
