[package]
authors.workspace = true
description = "Edit Me"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pod-db"
publish = false
repository.workspace = true
version = "0.1.0"

[dependencies]
chrono.workspace = true
libsqlite3-sys.workspace = true
pod-model.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
validator.workspace = true

[dev-dependencies]
tokio.workspace = true
