[package]
authors.workspace = true
description = "Domain models shared across the Pod crate ecosystem."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pod-model"
publish = false
repository.workspace = true
version = "0.1.0"

[dependencies]
getset.workspace = true
serde.workspace = true
validator.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
serde_json.workspace = true
