name: Build
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
      - "*-dev"
    tags:
      - "[0-9]+.*"
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          cache-save: "true"
      - name: Lint
        run: mise run lint
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-2022
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - if: runner.os == 'Linux'
        uses: ./.github/actions/setup
        with:
          cache-shared-key: v0-rust
      - if: runner.os != 'Linux'
        uses: ./.github/actions/setup-slim
        with:
          cache-shared-key: v0-rust
      - name: Check
        if: runner.os == 'Linux'
        run: mise run check
      - name: Check
        if: runner.os != 'Linux'
        run: cargo check --all-targets --all-features
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-2022
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - if: runner.os == 'Linux'
        uses: ./.github/actions/setup
        with:
          cache-shared-key: v0-rust
      - if: runner.os != 'Linux'
        uses: ./.github/actions/setup-slim
        with:
          cache-shared-key: v0-rust
      - name: Test (with coverage)
        if: runner.os == 'Linux'
        run: mise run test
      - name: Test
        if: runner.os != 'Linux'
        run: cargo nextest run --all-features
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-2022
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - if: runner.os == 'Linux'
        uses: ./.github/actions/setup
        with:
          cache-save: "true"
          cache-shared-key: v0-rust
      - if: runner.os != 'Linux'
        uses: ./.github/actions/setup-slim
        with:
          cache-save: "true"
          cache-shared-key: v0-rust
      - name: Build
        if: runner.os == 'Linux'
        run: mise run build
      - name: Build
        if: runner.os != 'Linux'
        run: cargo build --all-features
